<?php

namespace AppBundle\Repository;

/**
 * ReadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadingRepository extends \Doctrine\ORM\EntityRepository
{
}
