<?php

namespace AppBundle\Repository;

/**
 * UtilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilityRepository extends \Doctrine\ORM\EntityRepository
{
}
