<?php

namespace AppBundle\Repository;

/**
 * UtilityRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilityRateRepository extends \Doctrine\ORM\EntityRepository
{
}
